/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Register': ApiRouteHandler<{ name: string; email: string; password: string }, unknown, never>
    'Login': ApiRouteHandler<{ email: string; password: string }, unknown, never>
  }
}