// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/users": {
    params: {};
  };
  "/dashboard/facilities": {
    params: {};
  };
  "/dashboard/vouchers": {
    params: {};
  };
  "/dashboard/events": {
    params: {};
  };
  "/dashboard/restaurants": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/forgot-password" | "/reset-password" | "/verify-email" | "/dashboard" | "/dashboard/users" | "/dashboard/facilities" | "/dashboard/vouchers" | "/dashboard/events" | "/dashboard/restaurants" | "/dashboard/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/verify-email.tsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/users" | "/dashboard/facilities" | "/dashboard/vouchers" | "/dashboard/events" | "/dashboard/restaurants" | "/dashboard/settings";
  };
  "routes/dashboard/home.tsx": {
    id: "routes/dashboard/home";
    page: "/dashboard";
  };
  "routes/guards/admin-manager-guard.tsx": {
    id: "routes/guards/admin-manager-guard";
    page: "/dashboard/users" | "/dashboard/facilities";
  };
  "routes/dashboard/users.tsx": {
    id: "routes/dashboard/users";
    page: "/dashboard/users";
  };
  "routes/dashboard/facilities.tsx": {
    id: "routes/dashboard/facilities";
    page: "/dashboard/facilities";
  };
  "routes/guards/voucher-guard.tsx": {
    id: "routes/guards/voucher-guard";
    page: "/dashboard/vouchers";
  };
  "routes/dashboard/vouchers.tsx": {
    id: "routes/dashboard/vouchers";
    page: "/dashboard/vouchers";
  };
  "routes/guards/event-guard.tsx": {
    id: "routes/guards/event-guard";
    page: "/dashboard/events";
  };
  "routes/dashboard/events.tsx": {
    id: "routes/dashboard/events";
    page: "/dashboard/events";
  };
  "routes/guards/restaurant-guard.tsx": {
    id: "routes/guards/restaurant-guard";
    page: "/dashboard/restaurants";
  };
  "routes/dashboard/restaurants.tsx": {
    id: "routes/dashboard/restaurants";
    page: "/dashboard/restaurants";
  };
  "routes/dashboard/settings.tsx": {
    id: "routes/dashboard/settings";
    page: "/dashboard/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/verify-email": typeof import("./app/routes/verify-email.tsx");
  "routes/dashboard/layout": typeof import("./app/routes/dashboard/layout.tsx");
  "routes/dashboard/home": typeof import("./app/routes/dashboard/home.tsx");
  "routes/guards/admin-manager-guard": typeof import("./app/routes/guards/admin-manager-guard.tsx");
  "routes/dashboard/users": typeof import("./app/routes/dashboard/users.tsx");
  "routes/dashboard/facilities": typeof import("./app/routes/dashboard/facilities.tsx");
  "routes/guards/voucher-guard": typeof import("./app/routes/guards/voucher-guard.tsx");
  "routes/dashboard/vouchers": typeof import("./app/routes/dashboard/vouchers.tsx");
  "routes/guards/event-guard": typeof import("./app/routes/guards/event-guard.tsx");
  "routes/dashboard/events": typeof import("./app/routes/dashboard/events.tsx");
  "routes/guards/restaurant-guard": typeof import("./app/routes/guards/restaurant-guard.tsx");
  "routes/dashboard/restaurants": typeof import("./app/routes/dashboard/restaurants.tsx");
  "routes/dashboard/settings": typeof import("./app/routes/dashboard/settings.tsx");
};